name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org # npm publish required
      - name: Config Git # npm publish required
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Publish to NPM
        run: |
          npm i
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Settings -> Secrets and variables -> Actions -> Repository secrets

